// Generated by scripts/optimize-images.py. Edit scripts/image-sources.json to update descriptions.
export const galleries = {
  "scholarship": {
    "title": "Fondo Becario",
    "titleEn": "Scholarship Fund",
    "cover": "assets/projects/scholarship-cover.webp",
    "images": [
      {
        "src": "assets/projects/scholarship-01.webp",
        "width": 1600,
        "height": 963,
        "es": "Fondo Becario: panel de pagos, balance general e importación de archivos.",
        "en": "Scholarship Fund: payment dashboard, overall balance, and file imports."
      },
      {
        "src": "assets/projects/scholarship-02.webp",
        "width": 1600,
        "height": 765,
        "es": "Fondo Becario: inicio del panel de administración y navegación de módulos.",
        "en": "Scholarship Fund: administration home and module navigation."
      },
      {
        "src": "assets/projects/scholarship-03.webp",
        "width": 1600,
        "height": 962,
        "es": "Fondo Becario: pantalla de acceso con correo y contraseña.",
        "en": "Scholarship Fund: sign-in screen with email and password."
      },
      {
        "src": "assets/projects/scholarship-04.webp",
        "width": 1600,
        "height": 968,
        "es": "Fondo Becario: gestión de pagos y listado de aportes registrados.",
        "en": "Scholarship Fund: payment management and recorded contributions."
      },
      {
        "src": "assets/projects/scholarship-05.webp",
        "width": 1600,
        "height": 975,
        "es": "Fondo Becario: balance consolidado con filtro por año y resumen financiero.",
        "en": "Scholarship Fund: consolidated balance with year filter and financial summary."
      },
      {
        "src": "assets/projects/scholarship-06.webp",
        "width": 1600,
        "height": 894,
        "es": "Fondo Becario: detalle del balance con ingresos mensuales y egresos por categoría.",
        "en": "Scholarship Fund: balance details with monthly income and expenses by category."
      },
      {
        "src": "assets/projects/scholarship-07.webp",
        "width": 1600,
        "height": 883,
        "es": "Fondo Becario: registro de egresos con filtros por año y categoría.",
        "en": "Scholarship Fund: expense records with year and category filters."
      },
      {
        "src": "assets/projects/scholarship-08.webp",
        "width": 1600,
        "height": 862,
        "es": "Fondo Becario: formulario para crear una beca y definir sus requisitos.",
        "en": "Scholarship Fund: form for creating a scholarship and defining its requirements."
      },
      {
        "src": "assets/projects/scholarship-09.webp",
        "width": 1600,
        "height": 790,
        "es": "Fondo Becario: validación de inscripciones por estado de aprobación.",
        "en": "Scholarship Fund: application review by approval status."
      },
      {
        "src": "assets/projects/scholarship-10.webp",
        "width": 1600,
        "height": 977,
        "es": "Fondo Becario: carga y normalización de datos desde archivos Excel.",
        "en": "Scholarship Fund: uploading and normalizing data from Excel files."
      },
      {
        "src": "assets/projects/scholarship-11.webp",
        "width": 1600,
        "height": 628,
        "es": "Fondo Becario: registros de auditoría y filtros de actividad del sistema.",
        "en": "Scholarship Fund: audit log and system activity filters."
      },
      {
        "src": "assets/projects/scholarship-12.webp",
        "width": 1600,
        "height": 963,
        "es": "Fondo Becario: eliminación de pagos por fecha o intervalo de meses.",
        "en": "Scholarship Fund: removing payments by date or month range."
      }
    ]
  },
  "accounting": {
    "title": "Sistema Contable",
    "titleEn": "Accounting System",
    "cover": "assets/projects/accounting-cover.webp",
    "images": [
      {
        "src": "assets/projects/accounting-01.webp",
        "width": 1342,
        "height": 683,
        "es": "Sistema Contable: análisis financiero con filtros, indicadores y evolución mensual.",
        "en": "Accounting System: financial analysis with filters, indicators, and monthly trends."
      },
      {
        "src": "assets/projects/accounting-02.webp",
        "width": 1339,
        "height": 655,
        "es": "Sistema Contable: panel general con clientes, productos y comprobantes recientes.",
        "en": "Accounting System: overview with customers, products, and recent documents."
      },
      {
        "src": "assets/projects/accounting-03.webp",
        "width": 1098,
        "height": 628,
        "es": "Sistema Contable: gráficos de evolución mensual y principales clientes.",
        "en": "Accounting System: monthly trend charts and leading customers."
      },
      {
        "src": "assets/projects/accounting-04.webp",
        "width": 1102,
        "height": 710,
        "es": "Sistema Contable: distribución de movimientos y accesos a informes financieros.",
        "en": "Accounting System: transaction breakdown and financial report shortcuts."
      },
      {
        "src": "assets/projects/accounting-05.webp",
        "width": 1348,
        "height": 667,
        "es": "Sistema Contable: listado de asientos, filtros y resumen de la actividad contable.",
        "en": "Accounting System: journal entries, filters, and accounting activity summary."
      },
      {
        "src": "assets/projects/accounting-06.webp",
        "width": 1077,
        "height": 664,
        "es": "Sistema Contable: verificación de balance y últimos asientos creados.",
        "en": "Accounting System: balance verification and recently created journal entries."
      },
      {
        "src": "assets/projects/accounting-07.webp",
        "width": 1353,
        "height": 686,
        "es": "Sistema Contable: detalle de un asiento y comprobación de partida doble.",
        "en": "Accounting System: journal entry details and double-entry balance verification."
      },
      {
        "src": "assets/projects/accounting-08.webp",
        "width": 1095,
        "height": 426,
        "es": "Sistema Contable: movimientos de un asiento con columnas de debe y haber.",
        "en": "Accounting System: journal entry lines with debit and credit columns."
      },
      {
        "src": "assets/projects/accounting-09.webp",
        "width": 926,
        "height": 701,
        "es": "Sistema Contable: formato imprimible de un asiento contable.",
        "en": "Accounting System: printable journal entry document."
      },
      {
        "src": "assets/projects/accounting-10.webp",
        "width": 1335,
        "height": 681,
        "es": "Sistema Contable: gestión de facturas con importes, estados y acciones.",
        "en": "Accounting System: invoice management with amounts, statuses, and actions."
      },
      {
        "src": "assets/projects/accounting-11.webp",
        "width": 1322,
        "height": 689,
        "es": "Sistema Contable: vista de una factura con detalle de productos y totales.",
        "en": "Accounting System: invoice view with product details and totals."
      },
      {
        "src": "assets/projects/accounting-12.webp",
        "width": 1327,
        "height": 690,
        "es": "Sistema Contable: listado unificado de comprobantes y búsqueda por fecha.",
        "en": "Accounting System: unified document list and date search."
      },
      {
        "src": "assets/projects/accounting-13.webp",
        "width": 1330,
        "height": 683,
        "es": "Sistema Contable: gestión de notas de débito con estados e importes.",
        "en": "Accounting System: debit-note management with statuses and amounts."
      },
      {
        "src": "assets/projects/accounting-14.webp",
        "width": 1326,
        "height": 675,
        "es": "Sistema Contable: formulario de nueva nota de débito y resumen de totales.",
        "en": "Accounting System: new debit-note form and totals summary."
      },
      {
        "src": "assets/projects/accounting-15.webp",
        "width": 1330,
        "height": 681,
        "es": "Sistema Contable: listado y gestión de notas de crédito.",
        "en": "Accounting System: credit-note list and management."
      },
      {
        "src": "assets/projects/accounting-16.webp",
        "width": 1329,
        "height": 693,
        "es": "Sistema Contable: formulario para crear una nota de crédito.",
        "en": "Accounting System: form for creating a credit note."
      },
      {
        "src": "assets/projects/accounting-17.webp",
        "width": 1358,
        "height": 668,
        "es": "Sistema Contable: informe del libro de IVA digital.",
        "en": "Accounting System: digital VAT ledger report."
      }
    ]
  },
  "agromapa": {
    "title": "AgroMapa",
    "titleEn": "AgroMapa",
    "cover": "assets/projects/agromapa-cover.webp",
    "images": [
      {
        "src": "assets/projects/agromapa-01.webp",
        "width": 1600,
        "height": 766,
        "es": "AgroMapa: panel agrícola con filtros, indicadores y exportación de datos.",
        "en": "AgroMapa: agricultural dashboard with filters, indicators, and data exports."
      },
      {
        "src": "assets/projects/agromapa-02.webp",
        "width": 1600,
        "height": 766,
        "es": "AgroMapa: inicio del sistema con estadísticas generales y calendario agrícola.",
        "en": "AgroMapa: system home with overall statistics and an agricultural calendar."
      },
      {
        "src": "assets/projects/agromapa-03.webp",
        "width": 1600,
        "height": 771,
        "es": "AgroMapa: mapa de localidades y departamentos de Santa Fe.",
        "en": "AgroMapa: map of towns and departments in Santa Fe."
      },
      {
        "src": "assets/projects/agromapa-04.webp",
        "width": 1600,
        "height": 529,
        "es": "AgroMapa: indicadores de localidades, cultivo principal, temperatura y humedad.",
        "en": "AgroMapa: indicators for towns, main crop, temperature, and humidity."
      },
      {
        "src": "assets/projects/agromapa-05.webp",
        "width": 1600,
        "height": 768,
        "es": "AgroMapa: indicadores climáticos y rendimiento por cultivo, con aviso de error en el mapa.",
        "en": "AgroMapa: climate indicators and crop yields, with a map error message."
      },
      {
        "src": "assets/projects/agromapa-06.webp",
        "width": 672,
        "height": 186,
        "es": "AgroMapa: menú de reportes con exportación de datos e impresión del mapa.",
        "en": "AgroMapa: reports menu with data export and map printing."
      }
    ]
  },
  "chartier": {
    "title": "Hojalatería Chartier",
    "titleEn": "Hojalatería Chartier",
    "cover": "assets/projects/chartier-cover.webp",
    "images": [
      {
        "src": "assets/projects/chartier-01.webp",
        "width": 1600,
        "height": 877,
        "es": "Hojalatería Chartier: portada del sitio con presentación y accesos a servicios.",
        "en": "Hojalatería Chartier: website home with company introduction and service links."
      },
      {
        "src": "assets/projects/chartier-02.webp",
        "width": 1600,
        "height": 896,
        "es": "Hojalatería Chartier: catálogo de servicios de corte y plegado.",
        "en": "Hojalatería Chartier: cutting and bending services catalog."
      },
      {
        "src": "assets/projects/chartier-03.webp",
        "width": 1600,
        "height": 846,
        "es": "Hojalatería Chartier: ficha de productos con extractores eólicos.",
        "en": "Hojalatería Chartier: product details for wind-driven roof ventilators."
      },
      {
        "src": "assets/projects/chartier-04.webp",
        "width": 1600,
        "height": 898,
        "es": "Hojalatería Chartier: historia, experiencia y presentación de la empresa.",
        "en": "Hojalatería Chartier: company history, experience, and introduction."
      },
      {
        "src": "assets/projects/chartier-05.webp",
        "width": 1600,
        "height": 919,
        "es": "Hojalatería Chartier: canales de contacto y formulario de consulta.",
        "en": "Hojalatería Chartier: contact channels and inquiry form."
      }
    ]
  },
  "polo": {
    "title": "Polo Universitario",
    "titleEn": "University Center",
    "cover": "assets/projects/polo-cover.webp",
    "images": [
      {
        "src": "assets/projects/polo-01.webp",
        "width": 1600,
        "height": 797,
        "es": "Polo Universitario: portada del sitio institucional de San Justo.",
        "en": "University Center: home page of the San Justo institutional website."
      },
      {
        "src": "assets/projects/polo-02.webp",
        "width": 1350,
        "height": 678,
        "es": "Polo Universitario: comunidad educativa con perfiles, materiales y foros.",
        "en": "University Center: learning community with profiles, materials, and forums."
      },
      {
        "src": "assets/projects/polo-03.webp",
        "width": 1343,
        "height": 680,
        "es": "Polo Universitario: contenido de la comunidad y filtros de materiales educativos.",
        "en": "University Center: community content and educational material filters."
      },
      {
        "src": "assets/projects/polo-04.webp",
        "width": 967,
        "height": 605,
        "es": "Polo Universitario: perfil académico con acceso al currículum.",
        "en": "University Center: academic profile with a résumé link."
      },
      {
        "src": "assets/projects/polo-05.webp",
        "width": 1347,
        "height": 685,
        "es": "Polo Universitario: presentación institucional, objetivos y ubicación.",
        "en": "University Center: institutional overview, goals, and location."
      }
    ]
  },
  "comercio45": {
    "title": "Comercio 45",
    "titleEn": "Comercio 45",
    "cover": "assets/projects/comercio45-cover.webp",
    "images": [
      {
        "src": "assets/projects/comercio45-01.webp",
        "width": 1600,
        "height": 800,
        "es": "Comercio 45: portada de la Escuela Superior de Comercio N.º 45.",
        "en": "Comercio 45: home page of the Escuela Superior de Comercio No. 45."
      },
      {
        "src": "assets/projects/comercio45-02.webp",
        "width": 1600,
        "height": 802,
        "es": "Comercio 45: historia, misión e información institucional.",
        "en": "Comercio 45: history, mission, and institutional information."
      },
      {
        "src": "assets/projects/comercio45-03.webp",
        "width": 1600,
        "height": 781,
        "es": "Comercio 45: sección de estudiantes y navegación por año de cursado.",
        "en": "Comercio 45: student section and navigation by academic year."
      },
      {
        "src": "assets/projects/comercio45-04.webp",
        "width": 1600,
        "height": 844,
        "es": "Comercio 45: acceso al campus virtual para estudiantes y docentes.",
        "en": "Comercio 45: virtual campus access for students and teachers."
      },
      {
        "src": "assets/projects/comercio45-05.webp",
        "width": 364,
        "height": 258,
        "es": "Comercio 45: menú de inscripción y materiales propedéuticos.",
        "en": "Comercio 45: enrollment menu and introductory course materials."
      },
      {
        "src": "assets/projects/comercio45-06.webp",
        "width": 1600,
        "height": 811,
        "es": "Comercio 45: visualización de la ficha de inscripción en PDF.",
        "en": "Comercio 45: PDF enrollment form viewer."
      },
      {
        "src": "assets/projects/comercio45-07.webp",
        "width": 1600,
        "height": 792,
        "es": "Comercio 45: información sobre el curso propedéutico de ingreso.",
        "en": "Comercio 45: information about the introductory entrance course."
      }
    ]
  }
};
