"""Rebuild portfolio WebP assets and bilingual galleries from the original images.

Requires Python 3 and Pillow (python -m pip install Pillow).
Run from any directory: python scripts/optimize-images.py
Original files in Img/ are read only. No crops or visual content edits are made.
Gallery images are resized to at most 1600 px wide; covers to at most 800 px.
EXIF metadata is deliberately not copied into generated public assets.
"""

import json
from pathlib import Path

from PIL import Image, ImageOps


ROOT = Path(__file__).resolve().parents[1]
CATALOG = ROOT / 'scripts' / 'image-sources.json'
INVENTORY = ROOT / 'scripts' / 'image-inventory.json'
PROJECTS = ROOT / 'assets' / 'projects'
GALLERIES = ROOT / 'js' / 'galleries.js'


def encode(source, destination, width):
    with Image.open(source) as original:
        image = ImageOps.exif_transpose(original)
        original_size = [image.width, image.height]
        if image.mode not in ('RGB', 'RGBA'):
            image = image.convert('RGBA' if 'transparency' in image.info else 'RGB')
        if image.width > width:
            image = image.resize(
                (width, round(image.height * width / image.width)), Image.Resampling.LANCZOS
            )
        destination.parent.mkdir(parents=True, exist_ok=True)
        image.save(destination, 'WEBP', quality=86, method=6)
        return {
            'src': destination.relative_to(ROOT).as_posix(),
            'width': image.width,
            'height': image.height,
            'bytes': destination.stat().st_size,
            'sourceDimensions': original_size,
        }


def main():
    catalog = json.loads(CATALOG.read_text(encoding='utf-8'))
    galleries = {}
    used = {}
    generated = []
    for key, project in catalog['projects'].items():
        entries = []
        for number, entry in enumerate(project['images'], start=1):
            source = ROOT / entry['source']
            output = encode(source, PROJECTS / f'{key}-{number:02d}.webp', 1600)
            used[entry['source']] = {'project': key, 'output': output['src']}
            generated.append({**output, 'source': entry['source'], 'kind': 'gallery'})
            entries.append({
                'src': output['src'], 'width': output['width'], 'height': output['height'],
                'es': entry['es'], 'en': entry['en'],
            })
        cover_source = project['images'][0]['source']
        cover = encode(ROOT / cover_source, PROJECTS / f'{key}-cover.webp', 800)
        generated.append({**cover, 'source': cover_source, 'kind': 'cover'})
        galleries[key] = {
            'title': project['title'], 'titleEn': project['titleEn'],
            'cover': cover['src'], 'images': entries,
        }

    avatar_source = catalog['portrait']
    portrait = encode(ROOT / avatar_source, ROOT / 'assets' / 'portrait.webp', 768)
    used[avatar_source] = {'project': None, 'output': portrait['src']}
    generated.append({**portrait, 'source': avatar_source, 'kind': 'portrait'})
    originals = []
    for source in sorted((ROOT / 'Img').rglob('*')):
        if source.suffix.lower() not in ('.jpg', '.jpeg', '.png'):
            continue
        relative = source.relative_to(ROOT).as_posix()
        with Image.open(source) as image:
            originals.append({
                'source': relative, 'width': image.width, 'height': image.height,
                'bytes': source.stat().st_size,
                'usage': used.get(relative, {'project': None, 'output': None, 'reason': 'Decorative background excluded from project galleries'}),
            })

    original_bytes = sum(item['bytes'] for item in originals)
    selected_bytes = sum(item['bytes'] for item in originals if item['source'] in used)
    output_bytes = sum(item['bytes'] for item in generated)
    inventory = {
        'notes': catalog['notes'],
        'summary': {
            'originalCount': len(originals), 'galleryImageCount': sum(len(p['images']) for p in galleries.values()),
            'coverCount': len(galleries), 'outputCount': len(generated),
            'originalBytes': original_bytes, 'usedOriginalBytes': selected_bytes,
            'outputBytesIncludingCovers': output_bytes,
            'sizeReductionPercentIncludingCovers': round((1 - output_bytes / selected_bytes) * 100, 1),
        },
        'originals': originals, 'generated': generated,
    }
    INVENTORY.write_text(json.dumps(inventory, ensure_ascii=False, indent=2) + '\n', encoding='utf-8')
    GALLERIES.parent.mkdir(exist_ok=True)
    GALLERIES.write_text(
        '// Generated by scripts/optimize-images.py. Edit scripts/image-sources.json to update descriptions.\n'
        + 'export const galleries = '
        + json.dumps(galleries, ensure_ascii=False, indent=2) + ';\n',
        encoding='utf-8',
    )
    print(json.dumps(inventory['summary'], indent=2))
    for item in generated:
        if item['kind'] in ('cover', 'portrait'):
            print(f"{item['src']}: {item['width']}x{item['height']}, {item['bytes']:,} bytes")


if __name__ == '__main__':
    main()
